### ISSUE TITLE
Enhancement: Support for default parameters

### ISSUE THREAD

**Issue by longshorej** [fommil/spray-json-shapeless#11]
First off, nice library! It's been helpful and I appreciate the work that went into it.

Any thoughts on adding a feature that considers a case classes default values if the serialized Json is missing a field? It could be used as a solution for gradual schema migration. I was thinking maybe it could be another `JsNullBehaviour` but couldn't figure out how to implement it.

For example,

``` scala
case class Test(a: Int, b: String, c: Int = 5)

"""{"a": 1, "b": "test"}""".parseJson.convertTo[Test] // instantiates as Test(1, "b", 5)
```

**Comment by fommil** [comment]
Hmm, that's interesting. Maybe we could take an HList of optional defaults. Want to have a go?

**Comment by milessabin** [comment]
Already done: https://github.com/milessabin/shapeless/pull/462 ;-)

**Comment by fommil** [comment]
@milessabin great! I was totally going to stall any PR with macros because otherwise I'd have to update the ScalaX description of my talk :-D

@longshorej I'm not going to be able to work on this for a month, but if you raise a PR maybe miles could merge (assuming write access to this repo?). I also won't have computer access but that should auto build a snapshot for you to use until I make an official release.

**Comment by fommil** [comment]
I think this is done now?
