### ISSUE TITLE
implicit not found in scala-2.10 when less specific implicit is user provided

### ISSUE THREAD

**Issue by fommil** [fommil/spray-json-shapeless#5]
The second test in "prefer non-trivial user customisable JsonFormats" does not compile in scala 2.10

This is a test to show that if the user provides a less specific implicit, the more specific derived one will be used instead.

Bizarrely, when I tried to move this into a separate file just for scala-2.11, it failed to compile and I have no idea why (I renamed all classes and `examples` => `extraexamples`). There might be a separate bug in that.

**Comment by milessabin** [comment]
I'm having trouble working out the intended semantics here ...

With 2.10.5, the reason that there's no `RootJsonFormat` for `StringEnum` is that there isn't a `RootJsonFormat` for either of `Blam` or `Flooma` because they've been excluded from `familyFomat` by the latter's requirement for a `NoExistingJsonFormat` which is unavailable because of the existence of `stringEnumFormat` for both of those two.

If I remove the requirement for `NoExistingJsonFormat` from `familyFormat` then all tests compile and pass on both 2.10.x and 2.11.x. So I'd be inclined to just remove the `NoExistingJsonFormat`/`Xor` gubbins (which looks a bit wacky IMO) and declare victory.

Is that acceptable, or do you have some (currently untested) need for `NoExistingJsonFormat` in some other project?

There might be a different issue about why the test compiled and passed with 2.11.x but before digging into that any further I'd like to unmuddy the waters.

**Comment by fommil** [comment]
the `NoExistingJsonFormat` stuff is there so that we don't try to derive a `RootJsonFormat[T]` if a `JsonFormat[T]` is already available. Without that, it was happily deriving more than it needed. I'm pretty surprised the tests pass if you remove it... that sounds like I'm missing some coverage there.

I think you're right... I think the 2.10 behaviour of not compiling is actually correct. And I'm surprised it compiles under 2.11. Perhaps this should be another "shouldn't compile" test.

**Comment by milessabin** [comment]
Can you put together a test or two that pin down the behaviour that you're expecting and then I'll take another look?

**Comment by milessabin** [comment]
I do recommend getting rid of the `NoExistingFormat` stuff unless you can prove that it's doing something useful that can't be done any otherway. If you can include a test that would help me decide on that that'd be very much appreciated.

**Comment by fommil** [comment]
ok, I'll take this ticket back and do that.

**Comment by fommil** [comment]
(it might be the case that it was working around something that has since been fixed in a more recent version of shapeless or the compiler)

**Comment by milessabin** [comment]
Possible ... FYI before doing anything I bumped the shapeless version to 2.2.4, but I would be surprised if that made a difference.

**Comment by milessabin** [comment]
I'll do the license change in a separate PR then ;-)

**Comment by fommil** [comment]
this seems to be a wild goose chase, I'll create a new ticket for it.
