### ISSUE TITLE
docs should encourage separate sbt project for model and formats

### ISSUE THREAD

**Issue by fommil** [fommil/spray-json-shapeless#6]
otherwise random compiler moods can result in doing things out of order and trivial examples will fail.

**Comment by agemooij** [comment]
That seems like a pretty major limitation because that is not a very natural split for most projects. Would everything work if I have a persistence library that uses `spray-json-shapeless` to serialize case classes outside of its own scope, i.e. from users using my library with their own case classes as input?

Could you explain what is causing this and whether there are other workarounds for it?

**Comment by fommil** [comment]
@agemooij compiler limitations, and when it happens no there is no workaround besides enforcing compilation order via module separation. I think it might have something to do with the order of some hashset of files that the compiler is generating.

I don't fully understand your usecase. Do you mean that you have a library that is going to accept `JsValue`s or that you're accepting arbitrary sealed families? In the latter, I don't even know how you'd define your API unless you're using `Product` / `Coproduct`. If the former, the consequence of this compilation stuff is that your downstream users would have to put their sealed families into a package called `domain` or something (good practice regardless) and then use `spray-json-shapeless` in a higher layer, e.g. in the one that is communicating with your persistence library.

That said, it might Just Work... the rules about when the compiler decides to break are a bit of an unknown entity (it works for our own tests, for example). We're already recommending that domain objects and formatters are in peer packages.

**Comment by agemooij** [comment]
Would different packges be enough? The issue mentions different sbt projects, which is a much more impactful requirement than simply making sure that the domain code and the generated formats are not in the same package.

My library has typical type-class style serialization methods that take a `T` and an implicit `RootJsonFormat[T]`.

I have written an implicit macro, made available at very low implicit priority, that creates an implicit format for any T that resembles a case class. I'd like my users not to have to define any json formats at all unless they explicitly want to customize serialization behavior.

My macro is by far not as powerful as your shapeless based implementation though. so my question boils down to: if my library were to contain an implicit macro that uses spray-json-shapeless to generate an implicit format instead of hand-generating one, would users of my library risk getting compiler problems? The formats will be generated from the library while the case classes would be in application code.

**Comment by milessabin** [comment]
The problem that @fommil is describing is a consequence of [SI-7755](https://issues.scala-lang.org/browse/SI-7755) which affects all attempts to use the macro API to extract subclasses from a common super-type.

If your macro uses the same mechanism then you'll be affected in the same way. If it doesn't and it doesn't matter because you only work with concrete product types (ie. individual case classes rather than sealed families of case classes) then you can safely ignore Sam's warning ... there's no problem when just products are involved.

If you are using coproduct types then one workaround is to define your model types in a package which does not depend on the package(s) in which derived type class instances are instantiated. So, if the model is in package `foo.model` and the derivation is in package `foo.use` and `foo.model` can be compiled without `foo.use` then you should be fine. Obviously putting the model in a separate SBT submodule, or a separate project is one way to achieve that, but you don't need to go quite that far.

**Comment by fommil** [comment]
@milessabin I've seen a case in the wild where different packages wasn't enough for a trivial example 
(hence this ticket), but it couldn't be reproduced in isolation so I suspect there is some magic with file ordering in the compiler.

**Comment by milessabin** [comment]
It's not just _different_ packages ... the independent compilation bit is crucial.

Nested packages are one, slightly surprising way to generate unexpected dependencies. For example `foo.use.model` is a problem, because it will create a cycle between package `foo.use` and `foo.use.model`. The cycle exists because in Scala child packages depend on their parent unlike in Java. So even if there were no substantial dependencies between the two this could be problematic WRT SI-7755. In many cases it would just be sufficient to un-nest the model, ie. to refactor to `foo.model` and `foo.use`.

**Comment by fommil** [comment]
@milessabin hehe, actually yes I'll check... the bozo with the problem might have been accessing the formats from a parent package. Perhaps I ought to document that stronger.

**Comment by agemooij** [comment]
@milessabin Thanks for the explanation!

My problem is that I'm writing a library instead of an application so I'm not the one writing the model classes. At the level of my library we are talking about individual case classes but those might contain nested fields of types that represent sealed trait hierarchies and I'd have to generate formats for the entire type tree.

If I understand it correctly, the model might be defined in the same package that also refers to my library ([stamina](https://github.com/scalapenos/stamina)) and its macro would generate formats inline at the call site, putting them back in the same package. In which packages my users define their model classes and their Stamina `Persisters` is out of my direct control, hence my worries.

Last question: do these compiler failures happen consistently? In other words: if I write a test that proofs that my library example project can safely use my library using macro-generated formats, does that proof that other projects/users will not have the problem either? Or will it just randomly fail once in a while?

**Comment by milessabin** [comment]
@agemooij it's consistent in my experience. I think we probably need a common resource describing the caveats around any project which uses `directKnownSubclasses` directly or indirectly ... that includes pretty much every single serialization library which uses either its own macros or shapeless.
